services:
  proxy-server:
    image: "distributed-datastore"
    container_name: "ProxyServer"
    volumes:
      - ../ProxyServer/src:/go/src/mathapp
    networks:
      - "datastore"
    ports:
      - "7000:7000"
    restart: unless-stopped

  first-server:
    image: "distributed-datastore"
    container_name: "Server0"
    volumes:
      - ../Server/src:/go/src/mathapp
    networks:
      - "datastore"
    ports:
      - "8010:8000"
    environment:
      ID: "0"
    restart: unless-stopped

  second-server:
    image: "distributed-datastore"
    container_name: "Server1"
    volumes:
      - ../Server/src:/go/src/mathapp
    networks:
      - "datastore"
    ports:
      - "8020:8000"
    environment:
      ID: "1"
    restart: unless-stopped

  third-server:
    image: "distributed-datastore"
    container_name: "Server2"
    volumes:
      - ../Server/src:/go/src/mathapp
    networks:
      - "datastore"
    ports:
      - "8030:8000"
    environment:
      ID: "2"
    restart: unless-stopped

  fourth-server:
    image: "distributed-datastore"
    container_name: "Server3"
    volumes:
      - ../Server/src:/go/src/mathapp
    networks:
      - "datastore"
    ports:
      - "8040:8000"
    environment:
      ID: "3"
    restart: unless-stopped

networks:
  datastore:
    name: "Distributed Datastore"